initial-reward-base: 10 # the number of points each objective initially rewards
initial-reward-per-player: 5 # how many points the starting value of each objective is increased by for each player (including the first one) - score is set on /bingo start, so players that join after the game starts will not increase the score.
initial-decrement: 10 # how much the reward for and item is decreased by the first time a player finds it
subsequent-decrement: 5 # how much the reward decreases by on each find other than the first
bingo-set-score-to-zero: false # whether other player will no longer gain points on finding items in your bingo
bingo-bonus-static: 0 # how many bonus points a bingo will award, regardless of how many points you received for said bingo's items
bingo-bonus-multiplier: 1.0 # how much items in a bingo are multiplied by, will round score increase to int. this is the BONUS, so a value of 0 means
                            # that no dynamic bonus will be given for bingos, and a value of 2 means that all the items in a bingo will award triple points.

overworld:
  - dirt
  - gravel
  - sand
  - clay
  - stone
  - cobblestone
  - andesite
  - diorite
  - granite
  - obsidian
  - mossy_cobblestone
  - bricks
  - terracotta
  - sandstone
  - snowball
  - prismarine
  - coal_block
  - gold_block
  - iron_block
  - redstone_block
  - lapis_block
  - copper_block
  - glass
  - melon
  - hay_block
  - dried_kelp_block
  - cactus
  - acacia_log
  - oak_log
  - spruce_log
  - dark_oak_log
  - jungle_log
  - birch_log
  - crafting_table
  - furnace
  - blast_furnace
  - smoker
  - barrel
  - pumpkin
  - cauldron
  - cartography_table
  - fletching_table
  - loom
  - grindstone
  - smithing_table
  - bell
  - composter
  - scaffolding
  - note_block
  - piston
  - oak_sapling
  - birch_sapling
  - wheat
  - raw_iron_block
  - raw_copper_block
  - raw_gold_block
  - cut_copper
  - brown_mushroom
  - red_mushroom
  - sugar_cane
  - moss_block
  - chiseled_stone_bricks
  - chiseled_deepslate
  - iron_bars
  - chain
  - lily_pad
  - redstone
  - repeater
  - comparator
  - sticky_piston
  - target
  - tnt
  - hopper_minecart
  - powered_rail
  - rail
  - apple
  - bow
  - arrow
  - coal
  - charcoal
  - diamond
  - emerald
  - lapis_lazuli
  - raw_iron
  - iron_ingot
  - raw_copper
  - copper_ingot
  - raw_gold
  - gold_ingot
  - golden_axe
  - iron_shovel
  - diamond_sword
  - golden_apple
  - bucket
  - water_bucket
  - lava_bucket
  - clay
  - brick
  - cod
  - salmon
  - tropical_fish
  - glow_ink_sac
  - cookie
  - ender_pearl
  - rotten_flesh
  - iron_nugget
  - gold_nugget
  - fermented_spider_eye
  - glistering_melon_slice
  - golden_carrot
  - potion
  - item_frame
  - book
  - carrot
  - potato
  - baked_potato
  - firework_rocket
  - firework_star
  - rabbit_hide
  - armor_stand
  - crossbow
  - lantern
  - compass
  - clock
nether:
  - enchanting_table
  - bone_block
  - diamond_block
  - emerald_block
  - bookshelf
  - anvil
  - calcite
  - amethyst_block
  - netherrack
  - respawn_anchor
  - blaze_rod
  - fire_charge
  - nether_wart
  - quartz
  - warped_fungus_on_a_stick
  - observer
  - glowstone
  - chiseled_quartz_block
  - magma_block
  - soul_sand
  - soul_soil
  - basalt
  - ancient_debris
  - shroomlight
  - warped_stem
  - crimson_stem
  - blackstone
  - nether_bricks
  - red_nether_bricks
  - brewing_stand
colored: # these are separate from the other categories to allow all color variants without inflating the rates of these blocks
  - wool
  - stained_glass
  - terracotta
  - concrete
  - glazed_terracotta
  - concrete_powder
colors:
  - green
  - lime
  - black
  - blue
  - red
  - brown
  - white
  - yellow
  - light_blue
  - light_gray
  - magenta
  - orange
  - pink
  - cyan
  - gray
  - purple